# Generated by Django 4.2.3 on 2023-07-17 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kbgpt_app', '0003_botfilesmodel_botmodel_clientmodel_filemodel_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='botfilesmodel',
            table='bots_files',
        ),
        migrations.AlterModelTable(
            name='botmodel',
            table='bots',
        ),
        migrations.AlterModelTable(
            name='clientmodel',
            table='clients',
        ),
        migrations.AlterModelTable(
            name='filemodel',
            table='files',
        ),
    ]
