# Generated by Django 4.2.3 on 2023-07-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbgpt_app', '0004_alter_botfilesmodel_table_alter_botmodel_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botmodel',
            name='client_id',
        ),
        migrations.AddField(
            model_name='botmodel',
            name='group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
