# Generated by Django 4.2.3 on 2023-07-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbgpt_app', '0005_remove_botmodel_client_id_botmodel_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botmodel',
            name='group',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
