# Generated by Django 4.2.3 on 2023-07-17 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kbgpt_app', '0007_alter_botmodel_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botmodel',
            name='group',
        ),
    ]
