# Generated by Django 4.2.3 on 2023-07-17 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('kbgpt_app', '0008_remove_botmodel_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmodel',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
            preserve_default=False,
        ),
    ]
