# Generated by Django 4.2.3 on 2023-07-29 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kbgpt_app', '0011_botfilemodel_delete_botfilesmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='botfilemodel',
            table='bot_files',
        ),
    ]
