# Generated by Django 4.2.3 on 2023-07-29 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kbgpt_app', '0013_alter_botfilemodel_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botfilemodel',
            name='status',
        ),
    ]
