# Generated by Django 4.2.3 on 2023-07-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbgpt_app', '0014_remove_botfilemodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='botfilemodel',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='processing', max_length=255),
        ),
    ]
