# Generated by Django 4.2.3 on 2023-07-29 15:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kbgpt_app', '0016_rename_bot_id_botfilemodel_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmodel',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
