# Generated by Django 4.2.3 on 2023-07-29 15:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kbgpt_app', '0017_botmodel_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='botfilemodel',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
