# Generated by Django 4.2.3 on 2023-07-31 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbgpt_app', '0018_botfilemodel_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='botfilemodel',
            name='callback_url',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
